---
kind: pipeline
type: docker
name: buster

platform:
  os: linux
  arch: arm64

workspace:
  base: /drone
  path: kodi-src

trigger:
  ref:
  - refs/heads/master
  - refs/heads/rp64*
  - refs/tags/*

steps:
# Stage 1: build Kodi alone
- name: build_kodi
  image: sigmaris/kodibuilder:buster
  environment:
    KODI_DISTRO_CODENAME: buster
  commands:
  - cd ..
  - mkdir kodi-build-buster
  - cd kodi-build-buster
  - ../kodi-src/docker/build_kodi.sh
  - rm -f packages/kodi-*-aarch64-Unspecified.deb
  - cd ..
  - tar cjvf kodi-build-buster.tar.bz2 kodi-build-buster
  when:
    ref:
      exclude:
      - refs/tags/*-addons

# Stage 2: build addons for tag with -addons
- name: build_addons
  image: sigmaris/kodibuilder:buster
  environment:
    KODI_DISTRO_CODENAME: buster
  commands:
  - cd ..
  - kodi-src/docker/extract_build_tarball.sh buster
  - cd kodi-build-buster
  - ../kodi-src/docker/build_addons.sh
  when:
    ref:
      include:
      - refs/tags/*-addons

# Publish kodi build artifacts
- name: publish_kodi
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /drone/kodi-build-buster.tar.bz2
    - /drone/kodi-build-buster/packages/*.deb
    checksum:
    - md5
    - sha1
    - sha256
  depends_on:
  - build_kodi
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-addons

# Publish addons build artifacts
- name: publish_addons
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /drone/kodi-build-buster/build/addons_build/*.deb
    checksum:
    - md5
    - sha1
    - sha256
  depends_on:
  - build_addons
  when:
    event: tag
    ref:
      include:
      - refs/tags/*-addons

---
kind: pipeline
type: docker
name: bullseye

platform:
  os: linux
  arch: arm64

workspace:
  base: /drone
  path: kodi-src

trigger:
  ref:
  - refs/heads/master
  - refs/heads/rp64*
  - refs/tags/*

steps:
# Stage 1: Build Kodi alone
- name: build_kodi
  image: sigmaris/kodibuilder:bullseye
  environment:
    KODI_DISTRO_CODENAME: bullseye
  commands:
  - cd ..
  - mkdir kodi-build-bullseye
  - cd kodi-build-bullseye
  - ../kodi-src/docker/build_kodi.sh
  - rm -f packages/kodi-*-aarch64-Unspecified.deb
  - cd ..
  - tar cjvf kodi-build-bullseye.tar.bz2 kodi-build-bullseye
  when:
    ref:
      exclude:
      - refs/tags/*-addons

# Stage 2: build addons for tag with -addons
- name: build_addons
  image: sigmaris/kodibuilder:bullseye
  environment:
    KODI_DISTRO_CODENAME: bullseye
  commands:
  - cd ..
  - kodi-src/docker/extract_build_tarball.sh bullseye
  - cd kodi-build-bullseye
  - ../kodi-src/docker/build_addons.sh
  when:
    ref:
      include:
      - refs/tags/*-addons

# Publish kodi build artifacts
- name: publish_kodi
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /drone/kodi-build-bullseye.tar.bz2
    - /drone/kodi-build-bullseye/packages/*.deb
    checksum:
    - md5
    - sha1
    - sha256
  depends_on:
  - build_kodi
  when:
    event: tag
    ref:
      exclude:
      - refs/tags/*-addons

# Publish addons build artifacts
- name: publish_addons
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - /drone/kodi-build-bullseye/build/addons_build/*.deb
    checksum:
    - md5
    - sha1
    - sha256
  depends_on:
  - build_addons
  when:
    event: tag
    ref:
      include:
      - refs/tags/*-addons
