SET(CMAKE_C_COMPILER gcc)
SET(CMAKE_CXX_COMPILER g++)
SET(CMAKE_ASM_COMPILER gcc)
SET(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} -c")

SET(CMAKE_AR gcc-ar CACHE FILEPATH "Archiver" FORCE)
SET(CMAKE_RANLIB gcc-ranlib CACHE FILEPATH "Ranlib" FORCE)
SET(CMAKE_C_AR gcc-ar)
SET(CMAKE_CXX_AR gcc-ar)
SET(CMAKE_C_RANLIB gcc-ranlib)
SET(CMAKE_CXX_RANLIB gcc-ranlib)

IF(CMAKE_BUILD_TYPE MATCHES "Debug")
        ADD_DEFINITIONS(-rdynamic)
ENDIF()

